## **Import the Libraries**

In [0]:
import pandas as pd 
import numpy as np

**## Read data into dataframe from csv**

In [0]:
url = 'https://raw.githubusercontent.com/a-forty-two/DFE6/main/titanic.csv'
titanic = pd.read_csv(url)
titanic.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

## Data Cleansing

**## Capitalize and remove null values from all Columns**

In [0]:
titanic = titanic.set_index("PassengerId")
titanic = titanic.applymap(lambda x: x.capitalize() if isinstance(x, str) else x)
titanic = titanic.dropna()
titanic = titanic.drop(['Parch', 'SibSp', 'Embarked'], axis=1)
titanic

/home/spark-a1efa0ac-47e5-4c39-a074-8d/.ipykernel/68360/command-5973453172123657-2602043705:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  titanic = titanic.applymap(lambda x: x.capitalize() if isinstance(x, str) else x)

             Survived  Pclass  ...     Fare        Cabin
PassengerId                    ...
2                   1       1  ...  71.2833          C85
4                   1       1  ...  53.1000         C123
7                   0       1  ...  51.8625          E46
11                  1       3  ...  16.7000           G6
12                  1       1  ...  26.5500         C103
...               ...     ...  ...      ...          ...
872                 1       1  ...  52.5542          D35
873                 0       1  ...   5.0000  B51 b53 b55
880                 1       1  ...  83.1583          C50
888                 1       1  ...  30.0000          B42
890                 1       1  ...  30.0000         C148

[183 rows x 8 columns]

## **Write the dataframe into csv and store in Volumes**

In [0]:
%sql
CREATE VOLUME IF NOT EXISTS titanic_volume

In [0]:
volume_path = "/Volumes/pikapika/default/titanic_volume/titanic_cleansed_data.csv"
titanic.to_csv(volume_path, index=True)